markdown: kramdown

name: Jonathan "Duke" Leto
email: duke@leto.net
tagline: Open Source Citizen + Cryptocoin Developer
location: Earth
github: leto
twitter: dukeleto
twitter_sri: sha512-kQwpQTxJ73684KcaZ/AZSlpdueik0zyAkgu4emt3J7WhBLBoAJ5kL1hchAskhVRw7DtBkHWa07sZRIdIdtXChg==

default_donation: 5
default_currency: USD
donation_url: http://leto.github.com/freeyourself

amazon_payments_account_id:

bitcoin_address: 15pwvXdXo8XxJbQhG41d9xtDmr2UoCXoPP

paypal_email: jaleto@gmail.com

google_analytics:

ohloh_url:  http://ohloh.leto.net

linkedin_url: https://www.linkedin.com/in/jaleto/

base_url: https://github.com/leto/presentations/blob/master
